spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:prudentia}?sslmode=${DB_SSL:disable}
    username: ${DB_USERNAME:prudentia}
    password: ${DB_PASSWORD:prudentia}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  docker.compose:
    enabled: true
    lifecycle-management: start_only
    start.log-level: info

logging:
  level:
    root: ${LOG_LEVEL:info}
    org.hibernate.sql: debug