spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:prudentia}?sslmode=${DB_SSL:disable}
    username: ${DB_USERNAME:prudentia}
    password: ${DB_PASSWORD:prudentia}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  docker.compose:
    enabled: true
    lifecycle-management: start_only
    start.log-level: info

logging:
  level:
    com.zaxxer.hikari: debug
    org.hibernate.sql: debug