spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/prudentia?sslmode=${DB_SSL:prefer}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      idle-timeout: 10000
      max-lifetime: 600000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}

logging:
  level:
    root: ${LOG_LEVEL:info}